"""
=============================================================================
Binary to C-Array Converter for ESPboy ArduboyFX
=============================================================================
Description:
    Converts any .bin file (e.g. fxdata.bin, fxdta_rle.bin, fxdata_paged.bin)
    into a C/C++ source file containing a PROGMEM array.

Usage Instructions:

macOS / Linux:
    python3 bin2c.py <input.bin> <output.cpp> [variable_name]
    Examples:
        python3 bin2c.py fxdata.bin fxdta.cpp
        python3 bin2c.py fxdata_paged.bin fxdta.cpp fxdta

Windows:
    python bin2c.py <input.bin> <output.cpp> [variable_name]
    Examples:
        python bin2c.py fxdata.bin fxdta.cpp
        python bin2c.py fxdata_paged.bin fxdta.cpp fxdta
=============================================================================
"""

import sys
import os

def bin_to_c(input_file, output_file, var_name="fxdta"):
    print(f"Reading '{input_file}'...")
    with open(input_file, "rb") as f:
        data = f.read()

    print(f"Generating C-array ('{var_name}') into '{output_file}'...")
    with open(output_file, "w") as f:
        f.write("// Generated by bin2c.py for ESPboy ArduboyFX Library\n")
        f.write("#include <Arduino.h>\n\n")
        f.write(f"const uint8_t {var_name}[] PROGMEM = {{\n")

        lines = []
        for i in range(0, len(data), 16):
            chunk = data[i:i + 16]
            hex_bytes = ", ".join(f"0x{b:02X}" for b in chunk)
            lines.append("  " + hex_bytes)

        f.write(",\n".join(lines))
        f.write("\n};\n\n")
        f.write(f"const size_t {var_name}_len = {len(data)};\n")

    size_kb = len(data) / 1024.0
    print(f"Done! Created C-array file with {len(data)} bytes ({size_kb:.2f} KB).")

def main():
    if len(sys.argv) < 3:
        print("Error: Missing arguments.")
        print("Usage: python bin2c.py <input.bin> <output.cpp> [variable_name]")
        sys.exit(1)

    input_path = sys.argv[1]
    output_path = sys.argv[2]
    var_name = sys.argv[3] if len(sys.argv) > 3 else "fxdta"

    if not os.path.exists(input_path):
        print(f"Error: File '{input_path}' not found.")
        sys.exit(1)

    bin_to_c(input_path, output_path, var_name)

if __name__ == "__main__":
    main()