#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.15 ****/

using uint24_t = uint32_t;//__uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xff74;
constexpr uint24_t FX_DATA_BYTES = 35588;

constexpr uint24_t aboy = 0x000000;
constexpr uint24_t baloona = 0x000422;
constexpr uint24_t baloonb = 0x000442;
constexpr uint24_t baloonc = 0x00046E;
constexpr uint24_t baloond = 0x0004DC;
constexpr uint24_t baloone = 0x000562;
constexpr uint24_t baloonf = 0x00064E;
constexpr uint24_t baloong = 0x00075E;
constexpr uint24_t cloudb = 0x000892;
constexpr uint24_t cloudc = 0x0008B2;
constexpr uint24_t cloudd = 0x0008DE;
constexpr uint24_t cloude = 0x00094C;
constexpr uint24_t cloudf = 0x0009D2;
constexpr uint24_t cloudg = 0x000A70;
constexpr uint24_t cloudh = 0x000B26;
constexpr uint24_t coinb = 0x000C5A;
constexpr uint24_t coinc = 0x000C7A;
constexpr uint24_t coind = 0x000CA6;
constexpr uint24_t coine = 0x000D14;
constexpr uint24_t coinf = 0x000D9A;
constexpr uint24_t coing = 0x000E38;
constexpr uint24_t gameover = 0x000EEE;
constexpr uint24_t hglitch = 0x0026F0;
constexpr uint24_t menuscreen = 0x002BD2;
constexpr uint24_t newaboy = 0x0037D4;
constexpr uint24_t onebit = 0x003BF6;
constexpr uint24_t productions = 0x003F10;
constexpr uint24_t speaker = 0x0044BE;
constexpr uint24_t spherem = 0x004658;
constexpr uint24_t spheren = 0x004768;
constexpr uint24_t sphereo = 0x0048E4;
constexpr uint24_t spherep = 0x004ACC;
constexpr uint24_t sphereq = 0x004D20;
constexpr uint24_t spherer = 0x004FE0;
constexpr uint24_t spikeb = 0x00530C;
constexpr uint24_t spikec = 0x00532C;
constexpr uint24_t spiked = 0x005358;
constexpr uint24_t spikee = 0x0053C6;
constexpr uint24_t spikef = 0x00544C;
constexpr uint24_t spikeg = 0x0054EA;
constexpr uint24_t ssound = 0x0055A0;
constexpr uint24_t tv = 0x0055F6;
constexpr uint24_t vglitch = 0x006DF8;
constexpr uint24_t wonebit = 0x00763A;
constexpr uint24_t wproductions = 0x007954;
constexpr uint24_t youwin = 0x007F02;
