#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.15 ****/

//using uint24_t = __uint24;
using uint24_t = uint32;



// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xfcb1;
constexpr uint24_t FX_DATA_BYTES = 212716;

constexpr uint16_t FX_SAVE_PAGE  = 0xfff0;
constexpr uint24_t FX_SAVE_BYTES = 2;

constexpr uint24_t Action = 0x000000;
constexpr uint16_t ActionWidth  = 32;
constexpr uint16_t ActionHeight = 32;
constexpr uint8_t  ActionFrames = 10;

constexpr uint24_t Menu = 0x000504;
constexpr uint16_t MenuWidth  = 32;
constexpr uint16_t MenuHeight = 32;
constexpr uint8_t  MenuFrames = 9;

constexpr uint24_t Text = 0x000988;
constexpr uint16_t TextWidth  = 32;
constexpr uint16_t TextHeight = 32;
constexpr uint8_t  TextFrames = 15;

constexpr uint24_t Background = 0x00110C;
constexpr uint16_t BackgroundWidth  = 96;
constexpr uint16_t BackgroundHeight = 32;
constexpr uint8_t  BackgroundFrames = 7;

constexpr uint24_t Full = 0x001B90;
constexpr uint16_t FullWidth  = 128;
constexpr uint16_t FullHeight = 64;
constexpr uint8_t  FullFrames = 4;

constexpr uint24_t Gsname = 0x002B94;
constexpr uint16_t GsnameWidth  = 80;
constexpr uint16_t GsnameHeight = 23;

constexpr uint24_t Cabinroom = 0x002D78;
constexpr uint16_t CabinroomWidth  = 128;
constexpr uint16_t CabinroomHeight = 32;

constexpr uint24_t drop = 0x00317C;
constexpr uint16_t dropWidth  = 32;
constexpr uint16_t dropHeight = 32;
constexpr uint8_t  dropFrames = 6;

constexpr uint24_t lock = 0x003480;
constexpr uint16_t lockWidth  = 32;
constexpr uint16_t lockHeight = 32;

constexpr uint24_t coin = 0x003504;
constexpr uint16_t coinWidth  = 32;
constexpr uint16_t coinHeight = 32;
constexpr uint8_t  coinFrames = 5;

constexpr uint24_t weapons = 0x003788;
constexpr uint16_t weaponsWidth  = 32;
constexpr uint16_t weaponsHeight = 32;
constexpr uint8_t  weaponsFrames = 72;

constexpr uint24_t rarity = 0x005B8C;
constexpr uint16_t rarityWidth  = 32;
constexpr uint16_t rarityHeight = 32;
constexpr uint8_t  rarityFrames = 4;

constexpr uint24_t dummy = 0x005D90;
constexpr uint16_t dummyWidth  = 32;
constexpr uint16_t dummyHeight = 32;
constexpr uint8_t  dummyFrames = 6;

constexpr uint24_t mframe = 0x006394;
constexpr uint16_t mframeWidth  = 32;
constexpr uint16_t mframeHeight = 32;

constexpr uint24_t micons = 0x006418;
constexpr uint16_t miconsWidth  = 8;
constexpr uint16_t miconsHeight = 8;
constexpr uint8_t  miconsFrames = 7;

constexpr uint24_t SHDanime = 0x006454;
constexpr uint16_t SHDanimeWidth  = 128;
constexpr uint16_t SHDanimeHeight = 32;
constexpr uint8_t  SHDanimeFrames = 16;

constexpr uint24_t SHDanimeR = 0x00A458;
constexpr uint16_t SHDanimeRWidth  = 128;
constexpr uint16_t SHDanimeRHeight = 32;
constexpr uint8_t  SHDanimeRFrames = 16;

constexpr uint24_t ATKanime = 0x00E45C;
constexpr uint16_t ATKanimeWidth  = 128;
constexpr uint16_t ATKanimeHeight = 32;
constexpr uint8_t  ATKanimeFrames = 9;

constexpr uint24_t ATKanimeR = 0x010860;
constexpr uint16_t ATKanimeRWidth  = 128;
constexpr uint16_t ATKanimeRHeight = 32;
constexpr uint8_t  ATKanimeRFrames = 9;

constexpr uint24_t HEALanime = 0x012C64;
constexpr uint16_t HEALanimeWidth  = 128;
constexpr uint16_t HEALanimeHeight = 32;
constexpr uint8_t  HEALanimeFrames = 12;

constexpr uint24_t HEALanimeR = 0x015C68;
constexpr uint16_t HEALanimeRWidth  = 128;
constexpr uint16_t HEALanimeRHeight = 32;
constexpr uint8_t  HEALanimeRFrames = 12;

constexpr uint24_t HEALanimeS = 0x018C6C;
constexpr uint16_t HEALanimeSWidth  = 128;
constexpr uint16_t HEALanimeSHeight = 64;
constexpr uint8_t  HEALanimeSFrames = 2;

constexpr uint24_t HEALanimeSR = 0x019C70;
constexpr uint16_t HEALanimeSRWidth  = 128;
constexpr uint16_t HEALanimeSRHeight = 64;
constexpr uint8_t  HEALanimeSRFrames = 2;

constexpr uint24_t ENTanime = 0x01AC74;
constexpr uint16_t ENTanimeWidth  = 128;
constexpr uint16_t ENTanimeHeight = 32;
constexpr uint8_t  ENTanimeFrames = 21;

constexpr uint24_t ENTanimeR = 0x020078;
constexpr uint16_t ENTanimeRWidth  = 128;
constexpr uint16_t ENTanimeRHeight = 32;
constexpr uint8_t  ENTanimeRFrames = 21;

constexpr uint24_t kaire1 = 0x02547C;
constexpr uint16_t kaire1Width  = 32;
constexpr uint16_t kaire1Height = 32;
constexpr uint8_t  kaire1Frames = 20;

constexpr uint24_t kaire2 = 0x026880;
constexpr uint16_t kaire2Width  = 32;
constexpr uint16_t kaire2Height = 32;
constexpr uint8_t  kaire2Frames = 5;

constexpr uint24_t hana1 = 0x026B04;
constexpr uint16_t hana1Width  = 32;
constexpr uint16_t hana1Height = 32;
constexpr uint8_t  hana1Frames = 20;

constexpr uint24_t hana2 = 0x027F08;
constexpr uint16_t hana2Width  = 32;
constexpr uint16_t hana2Height = 32;
constexpr uint8_t  hana2Frames = 5;

constexpr uint24_t lyra1 = 0x02818C;
constexpr uint16_t lyra1Width  = 32;
constexpr uint16_t lyra1Height = 32;
constexpr uint8_t  lyra1Frames = 20;

constexpr uint24_t lyra2 = 0x029590;
constexpr uint16_t lyra2Width  = 32;
constexpr uint16_t lyra2Height = 32;
constexpr uint8_t  lyra2Frames = 5;

constexpr uint24_t zol1 = 0x029814;
constexpr uint16_t zol1Width  = 32;
constexpr uint16_t zol1Height = 32;
constexpr uint8_t  zol1Frames = 20;

constexpr uint24_t zol2 = 0x02AC18;
constexpr uint16_t zol2Width  = 32;
constexpr uint16_t zol2Height = 32;
constexpr uint8_t  zol2Frames = 5;

constexpr uint24_t draco1 = 0x02AE9C;
constexpr uint16_t draco1Width  = 32;
constexpr uint16_t draco1Height = 32;
constexpr uint8_t  draco1Frames = 20;

constexpr uint24_t draco2 = 0x02C2A0;
constexpr uint16_t draco2Width  = 32;
constexpr uint16_t draco2Height = 32;
constexpr uint8_t  draco2Frames = 5;

constexpr uint24_t exa1 = 0x02C524;
constexpr uint16_t exa1Width  = 32;
constexpr uint16_t exa1Height = 32;
constexpr uint8_t  exa1Frames = 20;

constexpr uint24_t exa2 = 0x02D928;
constexpr uint16_t exa2Width  = 32;
constexpr uint16_t exa2Height = 32;
constexpr uint8_t  exa2Frames = 5;

constexpr uint24_t chloroslime1 = 0x02DBAC;
constexpr uint16_t chloroslime1Width  = 32;
constexpr uint16_t chloroslime1Height = 32;
constexpr uint8_t  chloroslime1Frames = 10;

constexpr uint24_t chloroslime2 = 0x02E5B0;
constexpr uint16_t chloroslime2Width  = 32;
constexpr uint16_t chloroslime2Height = 32;
constexpr uint8_t  chloroslime2Frames = 5;

constexpr uint24_t aquaslime1 = 0x02E834;
constexpr uint16_t aquaslime1Width  = 32;
constexpr uint16_t aquaslime1Height = 32;
constexpr uint8_t  aquaslime1Frames = 10;

constexpr uint24_t aquaslime2 = 0x02F238;
constexpr uint16_t aquaslime2Width  = 32;
constexpr uint16_t aquaslime2Height = 32;
constexpr uint8_t  aquaslime2Frames = 5;

constexpr uint24_t blazeslime1 = 0x02F4BC;
constexpr uint16_t blazeslime1Width  = 32;
constexpr uint16_t blazeslime1Height = 32;
constexpr uint8_t  blazeslime1Frames = 10;

constexpr uint24_t blazeslime2 = 0x02FEC0;
constexpr uint16_t blazeslime2Width  = 32;
constexpr uint16_t blazeslime2Height = 32;
constexpr uint8_t  blazeslime2Frames = 5;

constexpr uint24_t thorny1 = 0x030144;
constexpr uint16_t thorny1Width  = 32;
constexpr uint16_t thorny1Height = 32;
constexpr uint8_t  thorny1Frames = 10;

constexpr uint24_t thorny2 = 0x030B48;
constexpr uint16_t thorny2Width  = 32;
constexpr uint16_t thorny2Height = 32;
constexpr uint8_t  thorny2Frames = 5;

constexpr uint24_t orchid1 = 0x030DCC;
constexpr uint16_t orchid1Width  = 32;
constexpr uint16_t orchid1Height = 32;
constexpr uint8_t  orchid1Frames = 10;

constexpr uint24_t orchid2 = 0x0317D0;
constexpr uint16_t orchid2Width  = 32;
constexpr uint16_t orchid2Height = 32;
constexpr uint8_t  orchid2Frames = 5;

constexpr uint24_t coyote1 = 0x031A54;
constexpr uint16_t coyote1Width  = 32;
constexpr uint16_t coyote1Height = 32;
constexpr uint8_t  coyote1Frames = 10;

constexpr uint24_t coyote2 = 0x032458;
constexpr uint16_t coyote2Width  = 32;
constexpr uint16_t coyote2Height = 32;
constexpr uint8_t  coyote2Frames = 5;

constexpr uint24_t spiro1 = 0x0326DC;
constexpr uint16_t spiro1Width  = 64;
constexpr uint16_t spiro1Height = 32;
constexpr uint8_t  spiro1Frames = 5;

constexpr uint24_t spiro2 = 0x0330E0;
constexpr uint16_t spiro2Width  = 32;
constexpr uint16_t spiro2Height = 32;
constexpr uint8_t  spiro2Frames = 4;

constexpr uint24_t alpha1 = 0x0332E4;
constexpr uint16_t alpha1Width  = 64;
constexpr uint16_t alpha1Height = 32;
constexpr uint8_t  alpha1Frames = 5;

constexpr uint24_t alpha2 = 0x033CE8;
constexpr uint16_t alpha2Width  = 32;
constexpr uint16_t alpha2Height = 32;
constexpr uint8_t  alpha2Frames = 4;
